### ISSUE TITLE
when i rename AppDelegate.m to app AppDelegate.mm build error 

### ISSUE THREAD

**Issue by bluesky0109** [dogo/SCLAlertView#121]
![7a31899d-28a2-45fe-b659-74930f5295f6](https://cloud.githubusercontent.com/assets/8929364/7933023/bf735624-094e-11e5-98fe-7f3dc71b80fe.png)

**Comment by dogo** [comment]
**Modules are enabled by default in new projects since XCode 5.** To enable them, go into your project build settings, search for "Modules" and set **"Enable Modules"** to **"YES"**. The **"Link Frameworks"** should be **"YES"** too:

![723su](https://cloud.githubusercontent.com/assets/1487375/5974731/d80d7b7a-a85e-11e4-9f70-8c131015b163.png)

PS : You can still release for older OSs (say iOS 4.3 or whatever). **Modules don't change how your code is built or any of the source code.**

**Comment by bluesky0109** [comment]
![pod error](https://cloud.githubusercontent.com/assets/8929364/7950681/c4a74664-09d0-11e5-9c64-f0cd402977b1.png)

I use XCode6.3 and I checked the CLANG_ENABLE_MODULES setting in every target of my client project, as well as every target in the Pods project, and every single one is set to YES, But still can not solve the problem,please give me some method to solve it.

**Comment by bluesky0109** [comment]
please release a new version of cocopods for Check for modules feature, thanks very much.

**Comment by dogo** [comment]
@bluesky0109 done 0.7.2
