### ISSUE TITLE
Alert view height problem when using it with long text in body

### ISSUE THREAD

**Issue by abbasmousavi** [dogo/SCLAlertView#127]
When using long text as body text, height of alert view is adjusted with the text, so it may render alert button and header out of view, also when rotating device, the height does not adjust to view height, as you can see in following screenshots.

![img_0066](https://cloud.githubusercontent.com/assets/1249875/8281601/d432d2c8-18fe-11e5-8368-cb91af353484.PNG)
![img_0067](https://cloud.githubusercontent.com/assets/1249875/8281602/d5c4918a-18fe-11e5-83b9-7ee25ada507d.PNG)

**Comment by dogo** [comment]
yep its a known issue

**Comment by ipaddr** [comment]
Have we tackle this issues? 
Since I able to scroll table view outside of SCLAlert as screen shot below shown.

<img width="325" alt="screen shot 2016-05-18 at 3 33 24 pm" src="https://cloud.githubusercontent.com/assets/5902218/15353955/966b5ac0-1d15-11e6-8b67-09a43bcf8ffc.png">

<img width="322" alt="screen shot 2016-05-18 at 3 33 37 pm" src="https://cloud.githubusercontent.com/assets/5902218/15353976/ad73d666-1d15-11e6-9cd8-b9475d1bbd84.png">

**Comment by ciumexan** [comment]
i have the exact same issue, with the alert not rendering in front of view but on the top...

**Comment by vinayakpal** [comment]
i need to expend the height of textfield as my texted exceeded the limit as i dont want my text to be in single line

**Comment by dogo** [comment]
Please fill the issue template
