### ISSUE TITLE
Add support to show only one alert view at the same time.

### ISSUE THREAD

**Issue by sunkehappy** [dogo/SCLAlertView#141]
I need a property (or something else with the same effect) to control whether it is permitted to show more than one alert view at the same time. Maybe this property's default value is YES. Then I could change it to NO to make sure there will only be one alert view shown at the same time.

Is this a good feature?

**Comment by dogo** [comment]
isVisible property should do the trick :P

```
//Returns if the alert is visible or not.
alert.isVisible;
```

**Comment by Simone67** [comment]
Hello, when I check .isVisible flag, it seem to be TRUE ever.. also if the alert is not yet call and is not yet visible..

**Comment by kalsky** [comment]
I think what he means is that the alert should be a singleton, so that if i'm calling showWaiting with no duration or 20 seconds duration, then while it runs i complete a task and would like to either dismiss the wait or show a success instead, it will currently add another alert (if you init a new one) or will behave wrong (if you use the same object and just call the showSuccess)

**Comment by bablu-joshi** [comment]
same issue

**Comment by dogo** [comment]
Please fill the issue template
