### ISSUE TITLE
Won't archive - Modules disabled

### ISSUE THREAD

**Issue by tlextrait** [dogo/SCLAlertView#60]
I can compile great but not in release mode (making an archive for ad-hoc distribution), the compiler says modules are disabled. Do I have a config issue?

"use of '@import' when modules disabled"

**Comment by dogo** [comment]
**Modules are enabled by default in new projects since XCode 5.** To enable them, go into your project build settings, search for "Modules" and set **"Enable Modules"** to **"YES"**. The **"Link Frameworks"** should be **"YES"** too:

![723su](https://cloud.githubusercontent.com/assets/1487375/5974731/d80d7b7a-a85e-11e4-9f70-8c131015b163.png)

PS : You can still release for older OSs (say iOS 4.3 or whatever). **Modules don't change how your code is built or any of the source code.**

**Comment by tlextrait** [comment]
Thanks a lot, I'm still a beginner when it comes to iOS dev!

**Comment by dogo** [comment]
No problem :)
