### ISSUE TITLE
"use of @import when modules are disabled error"

### ISSUE THREAD

**Issue by 4ntoine** [dogo/SCLAlertView#77]
I've just updated pods for my project and now i'm having "use of @import when modules are disabled error" because of `SCLAlertView.h`:

```
@import UIKit;
```

Modules are switched ON for the project:
![2015-03-09 13 09 55](https://cloud.githubusercontent.com/assets/846671/6551635/875f8840-c65d-11e4-97db-24c7d0dd9143.png)

How can i fix it?

**Comment by 4ntoine** [comment]
It's because of commit: https://github.com/dogo/SCLAlertView/commit/27e6dbf75e4914240b188f8ef6dd68363e1e4597

**Comment by dogo** [comment]
**Modules are enabled by default in new projects since XCode 5.** To enable them, go into your project build settings, search for "Modules" and set **"Enable Modules"** to **"YES"**. The **"Link Frameworks"** should be **"YES"** too:

![723su](https://cloud.githubusercontent.com/assets/1487375/5974731/d80d7b7a-a85e-11e4-9f70-8c131015b163.png)

PS : You can still release for older OSs (say iOS 4.3 or whatever). **Modules don't change how your code is built or any of the source code.**

**Comment by 4ntoine** [comment]
I've attached the screenshot where you can see modules are turned ON

**Comment by dogo** [comment]
It's very weird, was enable before? 
My Xcode is Version 6.2 (6C131e)

**Comment by robmaceachern** [comment]
I'm also having this issue. According to this comment, using `@import` isn't necessary since `#import` will be automatically mapped if modules are enabled, so I think https://github.com/dogo/SCLAlertView/commit/27e6dbf75e4914240b188f8ef6dd68363e1e4597 should be reverted.
https://github.com/jessesquires/JSQMessagesViewController/issues/541#issuecomment-58469043
